import type { Product } from '@/features/products/domain/product';

const SEED_PRODUCTS: Product[] = [
  {
    id: 'mbp14m3pro',
    name: 'MacBook Pro 14"',
    sku: 'MBP14M3PRO',
    description: 'Laptop z procesorem M3 Pro, 18 GB RAM, 512 GB SSD.',
    manufacturer: 'apple',
    category: 'komputery',
    features: ['bluetooth', 'wifi', 'usb-c', 'premium'],
    netPrice: 8129.27,
    grossPrice: 9999,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    minCartQuantity: 1,
    maxCartQuantity: 5,
  },
  {
    id: 'sgs24u256',
    name: 'Galaxy S24 Ultra',
    sku: 'SGS24U256',
    description: 'Smartfon z ekranem 6,8" i 256 GB pamięci.',
    manufacturer: 'samsung',
    category: 'telefony',
    features: ['bluetooth', 'wifi', 'usb-c', 'wodoodporny'],
    netPrice: 5121.14,
    grossPrice: 6299,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: true,
    stockQuantity: 45,
    minCartQuantity: 1,
    maxCartQuantity: 10,
  },
  {
    id: 'snwh1000xm5',
    name: 'Sony WH-1000XM5',
    sku: 'SNWH1000XM5',
    description: 'Bezprzewodowe słuchawki wokółuszne z redukcją szumów.',
    manufacturer: 'sony',
    category: 'rtv',
    features: ['bluetooth', 'bezprzewodowy', 'usb-c'],
    netPrice: 1300,
    grossPrice: 1599,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    minCartQuantity: 1,
    maxCartQuantity: 10,
  },
  {
    id: 'bswau28p40',
    name: 'Bosch Serie 6 WAU28P40',
    sku: 'BSWAU28P40',
    description: 'Pralka ładowana od frontu, 9 kg, 1400 obr./min.',
    manufacturer: 'bosch',
    category: 'agd',
    features: ['wifi', 'ekologiczny'],
    netPrice: 2682.11,
    grossPrice: 3299,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: false,
    isLimited: true,
    stockQuantity: 0,
    minCartQuantity: 1,
    maxCartQuantity: 2,
  },
  {
    id: 'xmsb8blk',
    name: 'Xiaomi Smart Band 8',
    sku: 'XMSB8BLK',
    description: 'Opaska sportowa z pomiarem tętna i natlenienia krwi.',
    manufacturer: 'xiaomi',
    category: 'akcesoria',
    features: ['bluetooth', 'wodoodporny', 'bezprzewodowy'],
    netPrice: 145.53,
    grossPrice: 179,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    minCartQuantity: 1,
    maxCartQuantity: 10,
  },
];

export function getProducts(): Product[] {
  return structuredClone(SEED_PRODUCTS);
}
